/**
 * The checked-in briefs and candidate sets, loaded and validated.
 *
 * These are pl-4's deliverable to pl-5 and to `@planner/itinerary` rather than
 * this package's private test data: the roster is a pure function of the brief,
 * so "a resort week runs lodging, food and practicalities" is a unit test given
 * a brief to run it against — and the composer's day packing needs candidates
 * that were written by hand rather than generated by the thing under test.
 *
 * They are **JSON, and loaded through this one helper**, for two reasons. JSON
 * has no import graph, so a package in another workspace reads it with a path
 * and no build step. And a fixture is only useful if it is *valid*, so it goes
 * through the real schema on the way in — a fixture that drifts out of the
 * contract fails here rather than in whichever suite happened to use it next.
 *
 * There is one file per `TripShape`, named for the shape, and
 * `fixtures.test.ts` asserts that the set is complete in both directions.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { candidateSchema, tripBriefSchema } from "../src/index.ts";
import type { Candidate, TripBrief, TripShape } from "../src/index.ts";

/** A brief and the candidates a fan-out plausibly produced for it. */
export interface TripFixture {
  brief: TripBrief;
  candidates: Candidate[];
}

/**
 * Local on purpose: nothing outside this file should validate "a fixture".
 * Pairing a brief with candidates is a test convenience, not a shape the tool
 * ever persists — a plan holds both, and that is `planDetailSchema`.
 */
const tripFixtureSchema = z.object({
  brief: tripBriefSchema,
  candidates: z.array(candidateSchema).min(1),
}) satisfies z.ZodType<TripFixture>;

/**
 * Resolved from this module's own URL rather than `process.cwd()`, so a suite
 * in another package reads the same files whatever directory vitest was started
 * from.
 */
const FIXTURE_DIR = fileURLToPath(new URL("./fixtures/", import.meta.url));

/**
 * One shape's fixture, parsed and validated.
 *
 * Throws on a fixture that does not fit the contract, which is the intended
 * behaviour: a caller has no useful way to proceed with an invalid brief, and
 * the failure should name the field rather than surface three layers later as a
 * roster that came out empty.
 */
export function loadFixture(shape: TripShape): TripFixture {
  const raw: unknown = JSON.parse(readFileSync(`${FIXTURE_DIR}${shape}.json`, "utf8"));
  return tripFixtureSchema.parse(raw);
}
