/**
 * Demo scenarios for the mock transport.
 *
 * Selection is by *path segment* of the pasted URL, not substring, so a real
 * URL that happens to contain the word "live" still gets the happy path. Every
 * `ErrorCode` in the taxonomy is reachable from this table plus three
 * interactions the table cannot express (bad input, cancel, unknown job) —
 * see `docs`-free note in `SCENARIOS` entries below.
 */

import type {
  ErrorCode,
  JobStatus,
  MediaVariant,
  ProbeResult,
  SubtitleTrack,
} from "@downloader/contract";

/** How the mock should play out a job once it has been created. */
export interface JobScript {
  failWith?: ErrorCode;
  /** Stage at which `failWith` is emitted. */
  failAt?: JobStatus;
  /** Report `percent: null` throughout — live capture, no Content-Length. */
  indeterminate?: boolean;
  /** Download tick indices at which the SSE connection is dropped. */
  dropStreamAt?: readonly number[];
  /** Publish a result whose retention window has already closed. */
  expiredResult?: boolean;
}

export interface Scenario {
  /** Matched against the pasted URL's path segments. */
  keyword: string;
  title: string;
  description: string;
  probeDelayMs: number;
  /** When set, the probe rejects with this code instead of returning a result. */
  probeError?: ErrorCode;
  /** Applied to the baseline probe result. */
  probe?: (base: ProbeResult) => ProbeResult;
  job: JobScript;
}

const SUBTITLES: SubtitleTrack[] = [
  {
    id: "sub-en",
    url: "https://cdn.example.com/subs/en.vtt",
    language: "en",
    label: "English",
    format: "vtt",
    autoGenerated: false,
  },
  {
    id: "sub-fr-auto",
    url: "https://cdn.example.com/subs/fr.vtt",
    language: "fr",
    label: "French (auto)",
    format: "vtt",
    autoGenerated: true,
  },
];

const DURATION_SEC = 1284;

function baseVariants(): MediaVariant[] {
  return [
    {
      id: "dash-2160p",
      protocol: "dash",
      url: "https://cdn.example.com/dash/video-2160.mpd",
      audioUrl: "https://cdn.example.com/dash/audio-en.mpd",
      hasVideo: true,
      hasAudio: false,
      container: "mp4",
      videoCodec: "hvc1.2.4.L153.B0",
      audioCodec: "mp4a.40.2",
      width: 3840,
      height: 2160,
      fps: 30,
      bitrateBps: 17_500_000,
      durationSec: DURATION_SEC,
      filesizeBytes: 2_808_000_000,
      filesizeIsEstimate: true,
      label: "2160p · HEVC + AAC (separate audio) · ~2.6 GB",
    },
    {
      id: "hls-1080p60",
      protocol: "hls",
      url: "https://cdn.example.com/hls/1080p60/index.m3u8",
      hasVideo: true,
      hasAudio: true,
      container: "mp4",
      videoCodec: "avc1.640028",
      audioCodec: "mp4a.40.2",
      width: 1920,
      height: 1080,
      fps: 60,
      bitrateBps: 6_200_000,
      durationSec: DURATION_SEC,
      filesizeBytes: 995_000_000,
      filesizeIsEstimate: true,
      label: "1080p60 · H.264 + AAC · ~950 MB",
    },
    {
      id: "hls-720p",
      protocol: "hls",
      url: "https://cdn.example.com/hls/720p/index.m3u8",
      hasVideo: true,
      hasAudio: true,
      container: "mp4",
      videoCodec: "avc1.4d401f",
      audioCodec: "mp4a.40.2",
      width: 1280,
      height: 720,
      fps: 30,
      bitrateBps: 2_800_000,
      durationSec: DURATION_SEC,
      filesizeBytes: 449_400_000,
      label: "720p · H.264 + AAC · 428 MB",
    },
    {
      id: "progressive-480p",
      protocol: "progressive",
      url: "https://cdn.example.com/files/480p.mp4",
      hasVideo: true,
      hasAudio: true,
      container: "mp4",
      videoCodec: "avc1.4d401e",
      audioCodec: "mp4a.40.2",
      width: 854,
      height: 480,
      fps: 30,
      bitrateBps: 1_100_000,
      durationSec: DURATION_SEC,
      filesizeBytes: 176_500_000,
      label: "480p · H.264 + AAC · 168 MB",
    },
    {
      id: "audio-aac",
      protocol: "progressive",
      url: "https://cdn.example.com/files/audio.m4a",
      hasVideo: false,
      hasAudio: true,
      container: "m4a",
      audioCodec: "mp4a.40.2",
      bitrateBps: 128_000,
      durationSec: DURATION_SEC,
      filesizeBytes: 20_500_000,
      language: "en",
      label: "Audio only · AAC 128 kbps · 20 MB",
    },
  ];
}

export function baseProbeResult(sourceUrl: string, probedAt: string): ProbeResult {
  return {
    sourceUrl,
    resolver: "browser-sniffer",
    title: "Sample broadcast — how streams are actually delivered",
    durationSec: DURATION_SEC,
    variants: baseVariants(),
    subtitles: SUBTITLES,
    requestContext: {
      headers: {
        Referer: sourceUrl,
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/131.0.0.0",
      },
    },
    drm: { protected: false, systems: [] },
    isLive: false,
    probedAt,
  };
}

const SUCCESS: JobScript = {};

export const DEFAULT_SCENARIO: Scenario = {
  keyword: "",
  title: "Happy path",
  description: "Five variants, determinate progress, finished file with a retention countdown.",
  probeDelayMs: 1_400,
  job: SUCCESS,
};

export const SCENARIOS: readonly Scenario[] = [
  {
    keyword: "slow",
    title: "Slow probe",
    description: "An 18-second browser probe — the case the analysing indicator exists for.",
    probeDelayMs: 18_000,
    job: SUCCESS,
  },
  {
    keyword: "live",
    title: "Live stream",
    description:
      "Live manifest. Creating a job without a recording duration is rejected with LIVE_STREAM_UNSUPPORTED; set one and the capture runs with indeterminate progress.",
    probeDelayMs: 1_200,
    probe: (base) => ({
      ...base,
      title: "Live: newsroom feed",
      isLive: true,
      durationSec: 0,
      variants: base.variants
        .filter((variant) => variant.protocol === "hls")
        .map((variant) => {
          const { filesizeBytes: _size, filesizeIsEstimate: _estimate, ...rest } = variant;
          return {
            ...rest,
            durationSec: 0,
            label: `${variant.label.split(" · ")[0] ?? ""} · live`,
          };
        }),
    }),
    job: { indeterminate: true },
  },
  {
    keyword: "indeterminate",
    title: "Unknown total size",
    description: "Chunked response with no Content-Length: percent stays null the whole way.",
    probeDelayMs: 1_200,
    probe: (base) => ({
      ...base,
      variants: base.variants.map((variant) => {
        const { filesizeBytes: _size, filesizeIsEstimate: _estimate, ...rest } = variant;
        return rest;
      }),
    }),
    job: { indeterminate: true },
  },
  {
    keyword: "flaky",
    title: "Dropping connection",
    description:
      "The event stream is cut twice mid-download. Watch the backoff, the reconnect, and the state jump forward when the job is re-fetched.",
    probeDelayMs: 1_200,
    job: { dropStreamAt: [3, 7] },
  },
  {
    keyword: "expired",
    title: "Expired file",
    description: "Completes, but the retention window has already closed — FILE_EXPIRED.",
    probeDelayMs: 1_000,
    job: { expiredResult: true },
  },
  {
    keyword: "drm",
    title: "DRM protected",
    description: "Widevine detected during the probe. Final, and offers no retry.",
    probeDelayMs: 2_200,
    probeError: "DRM_PROTECTED",
    job: SUCCESS,
  },
  {
    keyword: "nomedia",
    title: "No media found",
    description: "Page loaded, nothing playable requested.",
    probeDelayMs: 6_000,
    probeError: "NO_MEDIA_FOUND",
    job: SUCCESS,
  },
  {
    keyword: "auth",
    title: "Sign-in required",
    description: "Redirected to a login route.",
    probeDelayMs: 1_800,
    probeError: "AUTH_REQUIRED",
    job: SUCCESS,
  },
  {
    keyword: "geo",
    title: "Geo blocked",
    description: "Source refused the server's region.",
    probeDelayMs: 1_500,
    probeError: "GEO_BLOCKED",
    job: SUCCESS,
  },
  {
    keyword: "bot",
    title: "Bot challenge",
    description: "Anti-bot interstitial we could not clear.",
    probeDelayMs: 2_500,
    probeError: "BOT_CHALLENGE",
    job: SUCCESS,
  },
  {
    keyword: "offline",
    title: "Unreachable",
    description: "DNS or TLS failure. Retryable.",
    probeDelayMs: 900,
    probeError: "UNREACHABLE",
    job: SUCCESS,
  },
  {
    keyword: "blocked",
    title: "Blocked target",
    description: "SSRF guard rejected the address.",
    probeDelayMs: 200,
    probeError: "BLOCKED_TARGET",
    job: SUCCESS,
  },
  {
    keyword: "ratelimited",
    title: "Rate limited",
    description: "Per-IP limit on the probe endpoint. Retryable.",
    probeDelayMs: 200,
    probeError: "RATE_LIMITED",
    job: SUCCESS,
  },
  {
    keyword: "probetimeout",
    title: "Probe timeout",
    description: "The probe ran past its budget. Retryable.",
    probeDelayMs: 4_000,
    probeError: "TIMEOUT",
    job: SUCCESS,
  },
  {
    keyword: "boom",
    title: "Internal error",
    description: "Unhandled server-side failure.",
    probeDelayMs: 600,
    probeError: "INTERNAL",
    job: SUCCESS,
  },
  {
    keyword: "shutdown",
    title: "Analysis canceled",
    description: "The server stopped the probe mid-flight — a restart, typically. Not a timeout.",
    probeDelayMs: 800,
    probeError: "CANCELED",
    job: SUCCESS,
  },
  {
    keyword: "gone",
    title: "Variant expired",
    description: "The re-probe finds the signed URLs already dead. Retryable.",
    probeDelayMs: 1_000,
    job: { failWith: "VARIANT_GONE", failAt: "probing" },
  },
  {
    keyword: "huge",
    title: "Size limit exceeded",
    description: "Estimated size exceeds the cap, caught before any bytes are pulled.",
    probeDelayMs: 1_000,
    job: { failWith: "SIZE_LIMIT_EXCEEDED", failAt: "probing" },
  },
  {
    keyword: "dlfail",
    title: "Download failed",
    description: "Segment fetching gives up past the retry budget, mid-download. Retryable.",
    probeDelayMs: 1_000,
    job: { failWith: "DOWNLOAD_FAILED", failAt: "downloading" },
  },
  {
    keyword: "nodisk",
    title: "Disk full",
    description: "Storage volume filled up while writing segments.",
    probeDelayMs: 1_000,
    job: { failWith: "DISK_FULL", failAt: "downloading" },
  },
  {
    keyword: "jobtimeout",
    title: "Job timeout",
    description: "Hard wall-clock kill during the download.",
    probeDelayMs: 1_000,
    job: { failWith: "TIMEOUT", failAt: "downloading" },
  },
  {
    keyword: "muxfail",
    title: "Mux failed",
    description: "ffmpeg exits non-zero while joining the streams.",
    probeDelayMs: 1_000,
    job: { failWith: "MUX_FAILED", failAt: "muxing" },
  },
];

export function scenarioUrl(keyword: string): string {
  return keyword
    ? `https://videos.example.com/watch/${keyword}`
    : "https://videos.example.com/watch/sample";
}

/**
 * Longest keyword wins, so `probetimeout` is not shadowed by a future
 * `timeout` entry.
 */
export function findScenario(url: string): Scenario {
  let segments: string[];
  try {
    segments = new URL(url).pathname
      .split("/")
      .filter(Boolean)
      .map((s) => s.toLowerCase());
  } catch {
    return DEFAULT_SCENARIO;
  }
  const matches = SCENARIOS.filter((scenario) => segments.includes(scenario.keyword));
  matches.sort((a, b) => b.keyword.length - a.keyword.length);
  return matches[0] ?? DEFAULT_SCENARIO;
}
