/**
 * HTTP API contract.
 *
 * The API app validates requests with these schemas; the web app derives its
 * client types from the same file. Neither side hand-writes a duplicate shape.
 *
 * Both directions are covered. Request schemas guard the server against a
 * hostile client; response and event schemas guard *clients* — the browser
 * parsing an SSE frame or rehydrating `localStorage`, and the server parsing a
 * job row it read back out of SQLite. Anywhere the contract crosses a boundary
 * where the bytes are not already type-checked, one of these runs.
 *
 * Every schema is written `satisfies z.ZodType<T>` against the interface it
 * mirrors, so a field added to a type without a matching field here is a
 * compile error rather than a silent validation hole.
 */

import { z } from "zod";
import { ERROR_CODES } from "./errors.ts";
import type { AppErrorPayload } from "./errors.ts";
import { CONTAINER_OPTIONS, JOB_STATUSES } from "./job.ts";
import type {
  Job,
  JobEvent,
  JobListItem,
  JobListResult,
  JobOptions,
  JobProgress,
  JobResult,
} from "./job.ts";
import { DRM_SYSTEMS, STREAM_PROTOCOLS, SUBTITLE_FORMATS } from "./media.ts";
import type { DrmInfo, MediaVariant, ProbeResult, RequestContext, SubtitleTrack } from "./media.ts";

/** Schemes we will follow. Anything else is rejected as `INVALID_URL`. */
export const ALLOWED_SCHEMES = ["http:", "https:"] as const;

export const sourceUrlSchema = z
  .string()
  .trim()
  .min(1)
  .max(2048)
  .refine((value) => {
    try {
      return (ALLOWED_SCHEMES as readonly string[]).includes(new URL(value).protocol);
    } catch {
      return false;
    }
  }, "Must be an http(s) URL");

export const jobOptionsSchema = z.object({
  variantId: z.string().min(1).max(200).optional(),
  container: z.enum(CONTAINER_OPTIONS).optional(),
  embedSubtitles: z.boolean().optional(),
  subtitleLanguages: z.array(z.string().min(2).max(20)).max(10).optional(),
  audioOnly: z.boolean().optional(),
  liveDurationSec: z
    .number()
    .int()
    .positive()
    .max(4 * 60 * 60)
    .optional(),
}) satisfies z.ZodType<JobOptions>;

export const probeRequestSchema = z.object({
  url: sourceUrlSchema,
  /** Skip the probe cache and re-analyse. */
  refresh: z.boolean().optional(),
});

export const createJobRequestSchema = z.object({
  url: sourceUrlSchema,
  options: jobOptionsSchema.optional(),
});

export type ProbeRequest = z.infer<typeof probeRequestSchema>;
export type CreateJobRequest = z.infer<typeof createJobRequestSchema>;

// ---------------------------------------------------------------------------
// Contract schemas
//
// Runtime counterparts for the types that cross an untrusted boundary: SSE
// frames, rehydrated `localStorage`, and rows read back out of the job
// database. Media URLs are validated as strings, not URLs — reachability policy
// belongs to the SSRF guard, which knows about DNS and redirects; a schema that
// tried to enforce it would only give a false sense of having done so.
// ---------------------------------------------------------------------------

export const jobStatusSchema = z.enum(JOB_STATUSES);

export const errorCodeSchema = z.enum(ERROR_CODES);

export const appErrorPayloadSchema = z.object({
  code: errorCodeSchema,
  message: z.string(),
  retryable: z.boolean(),
  details: z.record(z.string(), z.unknown()).optional(),
}) satisfies z.ZodType<AppErrorPayload>;

export const drmInfoSchema = z.object({
  protected: z.boolean(),
  systems: z.array(z.enum(DRM_SYSTEMS)),
  evidence: z.string().optional(),
}) satisfies z.ZodType<DrmInfo>;

export const subtitleTrackSchema = z.object({
  id: z.string(),
  url: z.string(),
  language: z.string(),
  label: z.string(),
  format: z.enum(SUBTITLE_FORMATS),
  autoGenerated: z.boolean(),
}) satisfies z.ZodType<SubtitleTrack>;

export const mediaVariantSchema = z.object({
  id: z.string().min(1),
  protocol: z.enum(STREAM_PROTOCOLS),
  url: z.string().min(1),
  audioUrl: z.string().optional(),
  hasVideo: z.boolean(),
  hasAudio: z.boolean(),
  container: z.string().optional(),
  videoCodec: z.string().optional(),
  audioCodec: z.string().optional(),
  width: z.number().optional(),
  height: z.number().optional(),
  fps: z.number().optional(),
  bitrateBps: z.number().optional(),
  durationSec: z.number().optional(),
  filesizeBytes: z.number().optional(),
  filesizeIsEstimate: z.boolean().optional(),
  language: z.string().optional(),
  label: z.string(),
}) satisfies z.ZodType<MediaVariant>;

export const requestContextSchema = z.object({
  headers: z.record(z.string(), z.string()),
  expiresAt: z.string().optional(),
  proxyUrl: z.string().optional(),
}) satisfies z.ZodType<RequestContext>;

export const probeResultSchema = z.object({
  sourceUrl: z.string(),
  resolver: z.string(),
  title: z.string(),
  durationSec: z.number().optional(),
  thumbnailUrl: z.string().optional(),
  thumbnailPath: z.string().optional(),
  variants: z.array(mediaVariantSchema),
  subtitles: z.array(subtitleTrackSchema),
  requestContext: requestContextSchema,
  drm: drmInfoSchema,
  isLive: z.boolean(),
  probedAt: z.string(),
}) satisfies z.ZodType<ProbeResult>;

export const jobProgressSchema = z.object({
  stage: jobStatusSchema,
  percent: z.number().nullable(),
  downloadedBytes: z.number(),
  totalBytes: z.number().nullable(),
  segmentsDone: z.number().nullable(),
  segmentsTotal: z.number().nullable(),
  speedBps: z.number().nullable(),
  etaSec: z.number().nullable(),
  processedSec: z.number().nullable(),
}) satisfies z.ZodType<JobProgress>;

export const jobResultSchema = z.object({
  filename: z.string(),
  sizeBytes: z.number(),
  container: z.string(),
  durationSec: z.number().nullable(),
  downloadUrl: z.string(),
  expiresAt: z.string(),
}) satisfies z.ZodType<JobResult>;

export const jobSchema = z.object({
  id: z.string().min(1),
  sourceUrl: z.string(),
  variantId: z.string().nullable(),
  variant: mediaVariantSchema.nullable(),
  status: jobStatusSchema,
  progress: jobProgressSchema,
  result: jobResultSchema.nullable(),
  error: appErrorPayloadSchema.nullable(),
  attempts: z.number(),
  createdAt: z.string(),
  updatedAt: z.string(),
  finishedAt: z.string().nullable(),
  // `.optional()` as well as `.nullable()`, and it is not decoration: this key
  // is absent from every job already persisted under `downloader:jobs:v1`, and
  // `loadJobs` keeps only records that parse. A bare `.nullable()` rejects a
  // missing key outright (measured on zod 4.4.3), which would empty every
  // user's downloads list on their first load after deploy. `variant` above
  // survives on `.nullable()` alone only because it has always been written.
  thumbnailPath: z.string().nullable().optional(),
}) satisfies z.ZodType<Job>;

/**
 * Discriminated on `type`, so an unknown frame fails fast with a useful error
 * rather than being coerced into the first variant that happens to fit.
 */
export const jobEventSchema = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("status"),
    jobId: z.string().min(1),
    status: jobStatusSchema,
    at: z.string(),
  }),
  z.object({
    type: z.literal("progress"),
    jobId: z.string().min(1),
    progress: jobProgressSchema,
    at: z.string(),
  }),
  z.object({
    type: z.literal("probed"),
    jobId: z.string().min(1),
    probe: probeResultSchema,
    at: z.string(),
  }),
  z.object({
    type: z.literal("completed"),
    jobId: z.string().min(1),
    result: jobResultSchema,
    at: z.string(),
  }),
  z.object({
    type: z.literal("failed"),
    jobId: z.string().min(1),
    error: appErrorPayloadSchema,
    at: z.string(),
  }),
  z.object({
    type: z.literal("canceled"),
    jobId: z.string().min(1),
    error: appErrorPayloadSchema,
    at: z.string(),
  }),
  z.object({ type: z.literal("heartbeat"), at: z.string() }),
]) satisfies z.ZodType<JobEvent>;

/** Parses an SSE `data:` payload. Returns null for anything unrecognised. */
export function parseJobEvent(raw: string): JobEvent | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  const result = jobEventSchema.safeParse(parsed);
  return result.success ? result.data : null;
}

export interface ProbeResponse {
  probe: ProbeResult;
  /** True when served from cache rather than freshly analysed. */
  cached: boolean;
}

export interface JobResponse {
  job: Job;
}

export interface JobListResponse {
  /** `JobListItem`, not `Job`: the list does not carry `result.downloadUrl`. */
  jobs: JobListItem[];
  total: number;
}

export interface ErrorResponse {
  error: AppErrorPayload;
}

export const probeResponseSchema = z.object({
  probe: probeResultSchema,
  cached: z.boolean(),
}) satisfies z.ZodType<ProbeResponse>;

export const jobResponseSchema = z.object({ job: jobSchema }) satisfies z.ZodType<JobResponse>;

/**
 * Derived with `.omit`/`.extend` rather than written out, so a field added to
 * `jobSchema` or `jobResultSchema` reaches the list shape automatically and only
 * `downloadUrl` is ever the special case.
 */
export const jobListResultSchema = jobResultSchema.omit({
  downloadUrl: true,
}) satisfies z.ZodType<JobListResult>;

export const jobListItemSchema = jobSchema.extend({
  result: jobListResultSchema.nullable(),
}) satisfies z.ZodType<JobListItem>;

export const jobListResponseSchema = z.object({
  jobs: z.array(jobListItemSchema),
  total: z.number(),
}) satisfies z.ZodType<JobListResponse>;

export const errorResponseSchema = z.object({
  error: appErrorPayloadSchema,
}) satisfies z.ZodType<ErrorResponse>;

/**
 * Route table. Single source of truth for paths, so the client never
 * hardcodes a string the server can silently rename out from under it.
 */
export const ROUTES = {
  health: "/api/health",
  probe: "/api/probe",
  jobs: "/api/jobs",
  job: (id: string) => `/api/jobs/${id}`,
  jobEvents: (id: string) => `/api/jobs/${id}/events`,
  cancelJob: (id: string) => `/api/jobs/${id}/cancel`,
  /** `token` is opaque and unguessable — it is the capability, not the job id. */
  file: (token: string) => `/api/files/${token}`,
  /**
   * Same shape and same reason as `file`: the token is the capability. It also
   * exists so that no route anywhere takes a URL to fetch from a caller — the
   * client asks for an image this server already decided to fetch, by a name
   * only this server could have minted.
   */
  thumbnail: (token: string) => `/api/thumbnail/${token}`,
} as const;
