/**
 * Media description contracts.
 *
 * These types describe *what was found* at a source URL. They are produced by
 * resolvers (see `resolver.ts`) and consumed by the download engine and the UI.
 * Nothing here knows how a stream was discovered — that is deliberate, so the
 * yt-dlp fast path and the browser-sniffer generic path stay interchangeable.
 *
 * ## Why optional properties are written `?: T | undefined`
 *
 * The repo builds with `exactOptionalPropertyTypes`, under which `?: T` means
 * "absent or T" and rejects an explicit `undefined`. zod's `.optional()` yields
 * `T | undefined`, so a schema written against a plain `?: T` cannot satisfy
 * `z.ZodType<T>` — the property types are genuinely incompatible. Every type
 * here has a schema counterpart in `api.ts` that validates it at an untrusted
 * boundary, and those schemas are only worth having if the compiler proves they
 * match. Spelling out `| undefined` is what buys that proof. `JobOptions` in
 * `job.ts` is written the same way for the same reason.
 */

/** Transport used to deliver the media. */
export const STREAM_PROTOCOLS = [
  /** HTTP Live Streaming — `.m3u8` master/variant playlists over TS or fMP4 segments. */
  "hls",
  /** MPEG-DASH — `.mpd` manifest, usually with split audio/video adaptation sets. */
  "dash",
  /** A single addressable file (`.mp4`, `.webm`, `.mkv`) fetched with Range requests. */
  "progressive",
  /** Smooth Streaming, RTMP and other long-tail transports we may proxy through ffmpeg. */
  "other",
] as const;

export type StreamProtocol = (typeof STREAM_PROTOCOLS)[number];

/** Digital-rights-management systems we can *detect*. Detection only — see DrmInfo. */
export const DRM_SYSTEMS = ["widevine", "playready", "fairplay", "clearkey", "unknown"] as const;

export type DrmSystem = (typeof DRM_SYSTEMS)[number];

/** Subtitle serialisations we recognise. ffmpeg reads `vtt` and `srt` directly. */
export const SUBTITLE_FORMATS = ["vtt", "srt", "ttml", "unknown"] as const;

export type SubtitleFormat = (typeof SUBTITLE_FORMATS)[number];

/**
 * DRM status of a source.
 *
 * IMPORTANT distinction that every resolver must get right:
 *  - HLS AES-128 / SAMPLE-AES, where the decryption key is fetched from a URI
 *    named in the manifest (`EXT-X-KEY`), is ordinary transport encryption.
 *    ffmpeg handles it natively. That is NOT DRM for our purposes.
 *  - Widevine / PlayReady / FairPlay use EME + a licence server and a device
 *    key exchange. Those are out of scope by design: when `protected` is true
 *    the pipeline must stop and surface `DRM_PROTECTED` to the user.
 */
export interface DrmInfo {
  protected: boolean;
  systems: DrmSystem[];
  /** Human-readable evidence, e.g. "MPD ContentProtection urn:uuid:edef8ba9-…". */
  evidence?: string | undefined;
}

/** A subtitle/caption track discovered alongside the media. */
export interface SubtitleTrack {
  id: string;
  url: string;
  /** BCP-47 where known, e.g. "en", "fr-CA". */
  language: string;
  label: string;
  format: SubtitleFormat;
  /** True when the platform generated it automatically (usually lower quality). */
  autoGenerated: boolean;
}

/**
 * One downloadable rendition of the source.
 *
 * For DASH — and for HLS with `EXT-X-MEDIA` audio groups — video and audio live
 * at different URLs and must be muxed. When `audioUrl` is set, the engine feeds
 * ffmpeg two inputs and maps both streams into one output container.
 */
export interface MediaVariant {
  /** Stable within a single ProbeResult. The client echoes this back to start a job. */
  id: string;
  protocol: StreamProtocol;
  /** Manifest URL (HLS/DASH) or direct file URL (progressive). */
  url: string;
  /**
   * Other addresses serving **this same rendition**, in the order the source
   * declared them. `url` is the first; these are the ones after it.
   *
   * An HLS master may declare one rung once per CDN host — identical on every
   * attribute, differing in the hostname alone — and that repetition is not
   * noise: it is how a player survives one host going down, by retrying the
   * next entry with the same attributes (RFC 8216 §6.2.4). Before dl-45 the
   * resolver emitted one variant per host and the picker collapsed them back to
   * one row, which discarded the failover paths (dl-40).
   *
   * **Availability, not quality.** Two variants that differ only in how many of
   * these they carry are the same rendition; nothing may order, prefer or label
   * a variant *better* for having more. The engine uses them in exactly one
   * situation — the current host would not serve the bytes at all — and never
   * as a way around a refusal that would repeat everywhere, since an expired
   * signed URL is expired at every mirror.
   *
   * Absent, not `[]`, when there is only one address. Every URL here is
   * attacker-influenced exactly as `url` is and must clear the same SSRF check
   * (`urlsInProbeResult`).
   */
  alternateUrls?: string[] | undefined;
  /** Separate audio rendition to mux in, when the video track is silent. */
  audioUrl?: string | undefined;
  hasVideo: boolean;
  /**
   * `true` or `false` when a tier actually knows; **omitted when it does not**.
   *
   * `undefined` means "we did not look", and is deliberately distinct from
   * `false`, which means "we looked and there is none". The direct tier reaches
   * a plain file with one HEAD, and a HEAD carries `Content-Length` and
   * `Content-Type` and nothing about streams in either direction — so it has
   * nothing honest to put here (dl-42).
   *
   * Every consumer must branch on all three states rather than on truthiness.
   * In particular the engine maps an unverified audio stream *optionally*
   * (`-map 0:a:0?`), so ffmpeg keeps the track when it is there and does not
   * abort with `Stream map '0:a:0' matches no streams` when it is not.
   */
  hasAudio?: boolean | undefined;

  container?: string | undefined;
  videoCodec?: string | undefined;
  audioCodec?: string | undefined;
  width?: number | undefined;
  height?: number | undefined;
  fps?: number | undefined;
  bitrateBps?: number | undefined;
  durationSec?: number | undefined;

  /** Byte size. Often unknown for HLS/DASH until segments are enumerated. */
  filesizeBytes?: number | undefined;
  /** True when `filesizeBytes` was derived from bitrate × duration rather than measured. */
  filesizeIsEstimate?: boolean | undefined;

  /**
   * The language of the audio this rendition carries, when the source named one
   * — the `LANGUAGE` of the `EXT-X-MEDIA` rendition its `AUDIO` group points at,
   * or yt-dlp's `language` on the format. Absent otherwise, which is the common
   * case: a manifest with no audio groups declares no language at all.
   *
   * **Spelled as the source spelled it, and not normalised anywhere.** Both a
   * two-letter and a three-letter spelling reach this field — measured, not
   * assumed: the manifest fixtures in `resolvers/test/fixtures/manifests/`
   * carry `LANGUAGE="en"` and `LANGUAGE="fr"`, and the per-language ladder
   * ffmpeg's own hlsenc wrote for dl-40 carries `LANGUAGE="eng"` and
   * `LANGUAGE="fra"`. They are the same languages: `Intl.getCanonicalLocales("eng")`
   * returns `["en"]` on this runtime. Nothing here does that mapping, so as
   * strings they are unequal, and a consumer comparing two variants is comparing
   * what two producers wrote rather than what they meant.
   *
   * The picker renders it **only when two variants disagree on it** (dl-40).
   * That is not cosmetic: a ladder declared once per audio language is otherwise
   * several identical rows per rung, and a single-language video given a
   * Language column is a column of identical cells.
   */
  language?: string | undefined;
  /** Presentation string for the picker, e.g. "1080p60 · H.264 + AAC · ~420 MB". */
  label: string;
}

/**
 * Everything needed to re-issue a request for the media outside the browser.
 *
 * This is the single most under-appreciated part of the system. CDNs routinely
 * reject a manifest URL that is missing the `Referer` the player sent, the
 * session `Cookie`, or a signed query parameter with a short TTL. The engine
 * MUST replay this context on every segment fetch, not just the manifest.
 */
export interface RequestContext {
  /** Replayed verbatim. Typically Referer, Origin, User-Agent, Cookie, Authorization. */
  headers: Record<string, string>;
  /** ISO-8601. When set and in the past, the variant URLs are likely dead — re-probe. */
  expiresAt?: string | undefined;
  /** Proxy to route media fetches through, if one was needed to reach the source. */
  proxyUrl?: string | undefined;
}

/** The full result of analysing a source URL. */
export interface ProbeResult {
  sourceUrl: string;
  /** Which resolver produced this. Useful for debugging coverage gaps. */
  resolver: string;
  title: string;
  durationSec?: number | undefined;
  /**
   * The preview image **at the origin**, as a resolver found it (`og:image`,
   * `info.thumbnail`). Server-side only: it is page-controlled, so it is vetted
   * with the rest of the probe and fetched only through the guarded fetch. The
   * API strips it before the result reaches a client and puts `thumbnailPath`
   * in its place — see `thumbnails.ts` and `withThumbnailPath`.
   */
  thumbnailUrl?: string | undefined;
  /**
   * The preview image **as this API serves it**: `/api/thumbnail/<token>`, a
   * path on our own origin. Only the API sets this, and only on the way out.
   *
   * It is a second field rather than a re-use of `thumbnailUrl` because the two
   * are different things that must never be confused — one is an address a
   * hostile page chose and the browser must never be handed, the other is ours.
   * A single field would mean the same name denoting an origin URL inside the
   * server and a proxied path outside it, and nothing in the type would say
   * which side of the boundary a given value came from. Exactly one of the two
   * is populated at any point on the wire.
   */
  thumbnailPath?: string | undefined;
  /** Ordered best-first by the resolver; the UI may re-sort. */
  variants: MediaVariant[];
  subtitles: SubtitleTrack[];
  requestContext: RequestContext;
  drm: DrmInfo;
  /** True for live/DVR manifests, which need an explicit duration limit to download. */
  isLive: boolean;
  /** ISO-8601 timestamp of the probe. */
  probedAt: string;
}
