/**
 * Media description contracts.
 *
 * These types describe *what was found* at a source URL. They are produced by
 * resolvers (see `resolver.ts`) and consumed by the download engine and the UI.
 * Nothing here knows how a stream was discovered — that is deliberate, so the
 * yt-dlp fast path and the browser-sniffer generic path stay interchangeable.
 *
 * ## Why optional properties are written `?: T | undefined`
 *
 * The repo builds with `exactOptionalPropertyTypes`, under which `?: T` means
 * "absent or T" and rejects an explicit `undefined`. zod's `.optional()` yields
 * `T | undefined`, so a schema written against a plain `?: T` cannot satisfy
 * `z.ZodType<T>` — the property types are genuinely incompatible. Every type
 * here has a schema counterpart in `api.ts` that validates it at an untrusted
 * boundary, and those schemas are only worth having if the compiler proves they
 * match. Spelling out `| undefined` is what buys that proof. `JobOptions` in
 * `job.ts` is written the same way for the same reason.
 */

/** Transport used to deliver the media. */
export const STREAM_PROTOCOLS = [
  /** HTTP Live Streaming — `.m3u8` master/variant playlists over TS or fMP4 segments. */
  "hls",
  /** MPEG-DASH — `.mpd` manifest, usually with split audio/video adaptation sets. */
  "dash",
  /** A single addressable file (`.mp4`, `.webm`, `.mkv`) fetched with Range requests. */
  "progressive",
  /** Smooth Streaming, RTMP and other long-tail transports we may proxy through ffmpeg. */
  "other",
] as const;

export type StreamProtocol = (typeof STREAM_PROTOCOLS)[number];

/** Digital-rights-management systems we can *detect*. Detection only — see DrmInfo. */
export const DRM_SYSTEMS = ["widevine", "playready", "fairplay", "clearkey", "unknown"] as const;

export type DrmSystem = (typeof DRM_SYSTEMS)[number];

/** Subtitle serialisations we recognise. ffmpeg reads `vtt` and `srt` directly. */
export const SUBTITLE_FORMATS = ["vtt", "srt", "ttml", "unknown"] as const;

export type SubtitleFormat = (typeof SUBTITLE_FORMATS)[number];

/**
 * DRM status of a source.
 *
 * IMPORTANT distinction that every resolver must get right:
 *  - HLS AES-128 / SAMPLE-AES, where the decryption key is fetched from a URI
 *    named in the manifest (`EXT-X-KEY`), is ordinary transport encryption.
 *    ffmpeg handles it natively. That is NOT DRM for our purposes.
 *  - Widevine / PlayReady / FairPlay use EME + a licence server and a device
 *    key exchange. Those are out of scope by design: when `protected` is true
 *    the pipeline must stop and surface `DRM_PROTECTED` to the user.
 */
export interface DrmInfo {
  protected: boolean;
  systems: DrmSystem[];
  /** Human-readable evidence, e.g. "MPD ContentProtection urn:uuid:edef8ba9-…". */
  evidence?: string | undefined;
}

/** A subtitle/caption track discovered alongside the media. */
export interface SubtitleTrack {
  id: string;
  url: string;
  /** BCP-47 where known, e.g. "en", "fr-CA". */
  language: string;
  label: string;
  format: SubtitleFormat;
  /** True when the platform generated it automatically (usually lower quality). */
  autoGenerated: boolean;
}

/**
 * One downloadable rendition of the source.
 *
 * For DASH — and for HLS with `EXT-X-MEDIA` audio groups — video and audio live
 * at different URLs and must be muxed. When `audioUrl` is set, the engine feeds
 * ffmpeg two inputs and maps both streams into one output container.
 */
export interface MediaVariant {
  /** Stable within a single ProbeResult. The client echoes this back to start a job. */
  id: string;
  protocol: StreamProtocol;
  /** Manifest URL (HLS/DASH) or direct file URL (progressive). */
  url: string;
  /** Separate audio rendition to mux in, when the video track is silent. */
  audioUrl?: string | undefined;
  hasVideo: boolean;
  hasAudio: boolean;

  container?: string | undefined;
  videoCodec?: string | undefined;
  audioCodec?: string | undefined;
  width?: number | undefined;
  height?: number | undefined;
  fps?: number | undefined;
  bitrateBps?: number | undefined;
  durationSec?: number | undefined;

  /** Byte size. Often unknown for HLS/DASH until segments are enumerated. */
  filesizeBytes?: number | undefined;
  /** True when `filesizeBytes` was derived from bitrate × duration rather than measured. */
  filesizeIsEstimate?: boolean | undefined;

  language?: string | undefined;
  /** Presentation string for the picker, e.g. "1080p60 · H.264 + AAC · ~420 MB". */
  label: string;
}

/**
 * Everything needed to re-issue a request for the media outside the browser.
 *
 * This is the single most under-appreciated part of the system. CDNs routinely
 * reject a manifest URL that is missing the `Referer` the player sent, the
 * session `Cookie`, or a signed query parameter with a short TTL. The engine
 * MUST replay this context on every segment fetch, not just the manifest.
 */
export interface RequestContext {
  /** Replayed verbatim. Typically Referer, Origin, User-Agent, Cookie, Authorization. */
  headers: Record<string, string>;
  /** ISO-8601. When set and in the past, the variant URLs are likely dead — re-probe. */
  expiresAt?: string | undefined;
  /** Proxy to route media fetches through, if one was needed to reach the source. */
  proxyUrl?: string | undefined;
}

/** The full result of analysing a source URL. */
export interface ProbeResult {
  sourceUrl: string;
  /** Which resolver produced this. Useful for debugging coverage gaps. */
  resolver: string;
  title: string;
  durationSec?: number | undefined;
  /**
   * The preview image **at the origin**, as a resolver found it (`og:image`,
   * `info.thumbnail`). Server-side only: it is page-controlled, so it is vetted
   * with the rest of the probe and fetched only through the guarded fetch. The
   * API strips it before the result reaches a client and puts `thumbnailPath`
   * in its place — see `thumbnails.ts` and `withThumbnailPath`.
   */
  thumbnailUrl?: string | undefined;
  /**
   * The preview image **as this API serves it**: `/api/thumbnail/<token>`, a
   * path on our own origin. Only the API sets this, and only on the way out.
   *
   * It is a second field rather than a re-use of `thumbnailUrl` because the two
   * are different things that must never be confused — one is an address a
   * hostile page chose and the browser must never be handed, the other is ours.
   * A single field would mean the same name denoting an origin URL inside the
   * server and a proxied path outside it, and nothing in the type would say
   * which side of the boundary a given value came from. Exactly one of the two
   * is populated at any point on the wire.
   */
  thumbnailPath?: string | undefined;
  /** Ordered best-first by the resolver; the UI may re-sort. */
  variants: MediaVariant[];
  subtitles: SubtitleTrack[];
  requestContext: RequestContext;
  drm: DrmInfo;
  /** True for live/DVR manifests, which need an explicit duration limit to download. */
  isLive: boolean;
  /** ISO-8601 timestamp of the probe. */
  probedAt: string;
}
