/**
 * dl-42, end to end across the seam the defect actually lives on.
 *
 * The direct tier reaches a plain file with one HEAD, and a HEAD carries
 * `Content-Length` and `Content-Type` and nothing else. Until dl-42 the variant
 * it built asserted `hasAudio: true` anyway, and the engine believed it:
 * `-map 0:a`, no `?`, against a file with no audio stream at all.
 *
 * This file is in `api/` and not in `engine/` or `resolvers/` because the bug is
 * the *seam* between them — a resolver's claim consumed by the engine — and
 * `api` is the only package that may depend on both (`engine` importing
 * `resolvers` would invert the layering the tool is built on).
 *
 * The fixture is generated by the bundled ffmpeg and served from loopback;
 * nothing here touches the network. The container is `mkv` on purpose: an `.mp4`
 * source into the default `mp4` container sets `alreadyInTargetContainer` and
 * skips the mux stage entirely, which is why this survived since the direct tier
 * landed.
 */

import { spawn } from "node:child_process";
import fs from "node:fs/promises";
import http from "node:http";
import type { AddressInfo } from "node:net";
import os from "node:os";
import path from "node:path";
import { afterAll, beforeAll, describe, expect, test } from "vitest";
import { createEngine, resolveFfmpegPath } from "@downloader/engine";
import type { MediaVariant, ProbeResult } from "@downloader/contract";
import { DirectUrlResolver } from "@downloader/resolvers";

const FFMPEG = resolveFfmpegPath();
const CLIP_SECONDS = 2;
/** Real ffmpeg twice over — generating the clip and then remuxing it. */
const SLOW = 60_000;

let fixtureDir: string;
let storageDir: string;
let server: http.Server;
let origin: string;

function runFfmpeg(args: readonly string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(FFMPEG, [...args], {
      shell: false,
      windowsHide: true,
      stdio: ["ignore", "ignore", "pipe"],
    });
    let stderr = "";
    child.stderr?.setEncoding("utf8");
    child.stderr?.on("data", (chunk: string) => {
      stderr += chunk;
    });
    child.once("error", reject);
    child.once("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`ffmpeg exited ${code}: ${stderr.slice(-2000)}`));
    });
  });
}

/** A progressive MP4 with a video track and no audio track whatsoever. */
async function generateSilentClip(file: string): Promise<void> {
  await runFfmpeg([
    "-hide_banner",
    "-nostdin",
    "-loglevel",
    "error",
    "-y",
    "-f",
    "lavfi",
    "-i",
    `testsrc=size=160x120:rate=10:duration=${CLIP_SECONDS}`,
    "-an",
    "-c:v",
    "libx264",
    "-preset",
    "ultrafast",
    "-pix_fmt",
    "yuv420p",
    "-movflags",
    "+faststart",
    file,
  ]);
}

/** Every audio/video stream ffprobe-style, read back out of the produced file. */
async function streamKinds(file: string): Promise<string[]> {
  const output = await new Promise<string>((resolve, reject) => {
    const child = spawn(FFMPEG, ["-hide_banner", "-nostdin", "-i", file], {
      shell: false,
      windowsHide: true,
      stdio: ["ignore", "ignore", "pipe"],
    });
    let stderr = "";
    child.stderr?.setEncoding("utf8");
    child.stderr?.on("data", (chunk: string) => {
      stderr += chunk;
    });
    child.once("error", reject);
    // `-i` with no output is exit 1 by design; the stream table is on stderr.
    child.once("close", () => resolve(stderr));
  });
  return [...output.matchAll(/Stream #\d+:\d+.*?: (Video|Audio):/gu)].map((match) =>
    (match[1] ?? "").toLowerCase(),
  );
}

beforeAll(async () => {
  fixtureDir = await fs.mkdtemp(path.join(os.tmpdir(), "dl42-fixture-"));
  storageDir = await fs.mkdtemp(path.join(os.tmpdir(), "dl42-storage-"));
  await generateSilentClip(path.join(fixtureDir, "silent.mp4"));

  server = http.createServer((request, response) => {
    void (async () => {
      const name = path.basename(new URL(request.url ?? "/", "http://x").pathname);
      let body: Buffer;
      try {
        body = await fs.readFile(path.join(fixtureDir, name));
      } catch {
        response.writeHead(404).end();
        return;
      }
      const headers = {
        "content-type": "video/mp4",
        "content-length": String(body.length),
        "accept-ranges": "bytes",
      };
      if (request.method === "HEAD") {
        response.writeHead(200, headers).end();
        return;
      }
      response.writeHead(200, headers).end(body);
    })();
  });
  await new Promise<void>((resolve) => {
    server.listen(0, "127.0.0.1", resolve);
  });
  origin = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
}, SLOW);

afterAll(async () => {
  await new Promise<void>((resolve) => {
    server.closeAllConnections();
    server.close(() => resolve());
  });
  await fs.rm(fixtureDir, { recursive: true, force: true });
  await fs.rm(storageDir, { recursive: true, force: true });
});

async function probeFixture(): Promise<ProbeResult> {
  const resolver = new DirectUrlResolver();
  return await resolver.resolve(new URL(`${origin}/silent.mp4`), {
    signal: AbortSignal.timeout(15_000),
    timeoutMs: 15_000,
  });
}

describe("dl-42: a silent progressive file the direct tier never inspected", () => {
  test(
    "the resolver does not claim audio it never looked for",
    async () => {
      const probe = await probeFixture();
      const found = probe.variants[0] as MediaVariant;

      expect(found.protocol).toBe("progressive");
      expect(found.hasVideo).toBe(true);
      // Not `false` either: a HEAD says nothing about audio in *either*
      // direction, and "we looked and there is none" would be a second lie.
      expect(found.hasAudio).toBeUndefined();

      // The fixture really has no audio, so the claim was not merely unlucky.
      expect(await streamKinds(path.join(fixtureDir, "silent.mp4"))).toEqual(["video"]);
    },
    SLOW,
  );

  test(
    "downloads into a non-matching container instead of failing on -map 0:a",
    async () => {
      const probe = await probeFixture();
      const found = probe.variants[0] as MediaVariant;

      const engine = createEngine({ storageDir, maxFileSizeBytes: 64 * 1024 * 1024 });
      await engine.init();

      const stages: string[] = [];
      const outcome = await engine.download({
        jobId: "dl42-mkv",
        variant: found,
        requestContext: probe.requestContext,
        title: "silent",
        // mkv, not mp4: the source extension must differ from the target or
        // `alreadyInTargetContainer` skips the mux stage and proves nothing.
        options: { container: "mkv" },
        onStage: (stage) => stages.push(stage),
      });

      expect(stages).toEqual(["downloading", "muxing"]);
      expect(outcome.container).toBe("mkv");
      expect(outcome.sizeBytes).toBeGreaterThan(1000);

      // The video survived the remux and no audio track was invented.
      expect(await streamKinds(outcome.path)).toEqual(["video"]);
    },
    SLOW,
  );
});
