// @vitest-environment jsdom

/**
 * What the user chooses between a probe and a job, and the `JobOptions` those
 * choices add up to.
 *
 * See `progress-bar.test.tsx` for why the DOM arrives as a docblock rather than
 * a vitest project of its own.
 *
 * The claim worth pinning here is the default: **the panel starts on whatever
 * `pickDefaultVariantId` names**, not on the first or the tallest row. Anything
 * else and a user who presses Download without reading the table gets a silent
 * mux they did not ask for.
 */

import { afterEach, expect, test, vi } from "vitest";
import { cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import type { JobOptions } from "@downloader/contract";
import { ProbePanel } from "../src/components/ProbePanel.tsx";
import { pickDefaultVariantId } from "../src/lib/variants.ts";
import { probe, variants } from "./fixtures.ts";

afterEach(cleanup);

const SUBTITLES = [
  {
    id: "sub-en",
    url: "https://cdn.example.com/subs/en.vtt",
    language: "en",
    label: "English",
    format: "vtt" as const,
    autoGenerated: false,
  },
  {
    id: "sub-fr",
    url: "https://cdn.example.com/subs/fr.vtt",
    language: "fr",
    label: "French",
    format: "vtt" as const,
    autoGenerated: true,
  },
];

interface Spies {
  onDownload: ReturnType<typeof vi.fn<(options: JobOptions) => void>>;
  onReanalyse: ReturnType<typeof vi.fn<() => void>>;
}

function mount(result = probe(), options: { cached?: boolean; busy?: boolean } = {}): Spies {
  const spies: Spies = {
    onDownload: vi.fn<(options: JobOptions) => void>(),
    onReanalyse: vi.fn<() => void>(),
  };
  render(
    <ProbePanel
      probe={result}
      cached={options.cached ?? false}
      busy={options.busy ?? false}
      onDownload={spies.onDownload}
      onReanalyse={spies.onReanalyse}
    />,
  );
  return spies;
}

function download(): void {
  fireEvent.click(screen.getByRole("button", { name: "Download" }));
}

test("the panel opens on the variant `pickDefaultVariantId` names", () => {
  mount();

  const checked = (within(screen.getByRole("table")).getAllByRole("radio") as HTMLInputElement[])
    .filter((input) => input.checked)
    .map((input) => input.value);
  expect(checked).toEqual([pickDefaultVariantId(variants())]);
  // Spelled out rather than left to the helper: the tallest rendition is 2160p
  // and it is *not* the default, because its audio is a separate stream.
  expect(checked).toEqual(["v-1080"]);
});

test("the header names what was found and which resolver found it", () => {
  mount(probe(), { cached: true });

  expect(screen.getByRole("heading", { name: "A sample recording" })).toBeDefined();
  expect(screen.getByText("direct")).toBeDefined();
  expect(screen.getByText("cached")).toBeDefined();
  expect(screen.getByText(/12:34 · 3 renditions/u)).toBeDefined();
});

test("a single rendition is not pluralised", () => {
  mount(probe({ variants: variants().slice(1, 2) }));
  expect(screen.getByText(/1 rendition$/u)).toBeDefined();
});

test("pressing Download reports the current choices as JobOptions", () => {
  const spies = mount();

  download();
  expect(spies.onDownload).toHaveBeenCalledWith({
    variantId: "v-1080",
    container: "mp4",
    audioOnly: false,
    embedSubtitles: false,
  });
});

test("choosing another rendition and another container changes what is asked for", async () => {
  const user = userEvent.setup();
  const spies = mount();

  await user.click(
    (within(screen.getByRole("table")).getAllByRole("radio") as HTMLInputElement[]).find(
      (input) => input.value === "v-audio",
    ) as HTMLInputElement,
  );
  await user.selectOptions(screen.getByLabelText("Container"), "mkv");
  await user.click(screen.getByRole("checkbox", { name: "Audio only" }));

  download();
  expect(spies.onDownload).toHaveBeenCalledWith({
    variantId: "v-audio",
    container: "mkv",
    audioOnly: true,
    embedSubtitles: false,
  });
});

test("subtitles are offered, defaulted on, and named by language", () => {
  const spies = mount(probe({ subtitles: SUBTITLES }));

  const embed = screen.getByRole("checkbox", { name: "Embed subtitles (en, fr)" });
  expect((embed as HTMLInputElement).checked).toBe(true);
  expect(screen.getByText(/2 subtitle tracks/u)).toBeDefined();

  download();
  expect(spies.onDownload).toHaveBeenCalledWith({
    variantId: "v-1080",
    container: "mp4",
    audioOnly: false,
    embedSubtitles: true,
    subtitleLanguages: ["en", "fr"],
  });
});

test("a source with no subtitles disables the option rather than hiding it", () => {
  mount();

  const embed = screen.getByRole("checkbox", { name: "Embed subtitles" }) as HTMLInputElement;
  expect(embed.disabled).toBe(true);
  expect(embed.checked).toBe(false);
});

test("a live source is flagged and made to carry a duration", async () => {
  // A live manifest has no end, so a job without a limit is rejected with
  // LIVE_STREAM_UNSUPPORTED. The panel is where the limit is collected.
  const user = userEvent.setup();
  const spies = mount(probe({ isLive: true }));

  expect(screen.getByText("Live")).toBeDefined();
  const minutes = screen.getByLabelText("Record for (minutes)") as HTMLInputElement;
  expect(minutes.value).toBe("5");

  await user.clear(minutes);
  await user.type(minutes, "12");
  download();
  expect(spies.onDownload).toHaveBeenCalledWith({
    variantId: "v-1080",
    container: "mp4",
    audioOnly: false,
    embedSubtitles: false,
    liveDurationSec: 720,
  });
});

test("a source that is not live asks for no duration at all", () => {
  mount();
  expect(screen.queryByLabelText("Record for (minutes)")).toBeNull();
  expect(screen.queryByText("Live")).toBeNull();
});

test("a busy panel says so and cannot be pressed twice", () => {
  const spies = mount(probe(), { busy: true });

  const button = screen.getByRole("button", { name: "Starting…" });
  expect((button as HTMLButtonElement).disabled).toBe(true);
  fireEvent.click(button);
  expect(spies.onDownload).not.toHaveBeenCalled();
});

test("analysing again is always available, because the links expire", () => {
  const spies = mount(probe(), { busy: true });

  fireEvent.click(screen.getByRole("button", { name: "Analyse again" }));
  expect(spies.onReanalyse).toHaveBeenCalledOnce();
});
