import { readFileSync } from "node:fs";
import { AppError } from "@downloader/contract";
import { describe, expect, test } from "vitest";
import { parseDash, parseFrameRate, parseIsoDuration } from "../src/manifest/dash.ts";

function fixture(name: string): string {
  return readFileSync(new URL(`./fixtures/manifests/${name}`, import.meta.url), "utf8");
}

describe("scalar parsing", () => {
  test("ISO-8601 durations", () => {
    expect(parseIsoDuration("PT10M34.6S")).toBeCloseTo(634.6, 3);
    expect(parseIsoDuration("PT1H2M3.5S")).toBeCloseTo(3723.5, 3);
    expect(parseIsoDuration("P0Y0M0DT0H4M12.00S")).toBeCloseTo(252, 3);
    expect(parseIsoDuration("PT5M")).toBe(300);
    expect(parseIsoDuration("not a duration")).toBeUndefined();
    expect(parseIsoDuration(undefined)).toBeUndefined();
  });

  test("rational frame rates", () => {
    expect(parseFrameRate("60")).toBe(60);
    expect(parseFrameRate("30000/1001")).toBeCloseTo(29.97, 2);
    expect(parseFrameRate("24000/0")).toBeUndefined();
  });
});

describe("$Number$ SegmentTemplate manifest", () => {
  const base = "https://cdn.example.com/vod/tears-of-steel/manifest.mpd";
  const parsed = parseDash(fixture("dash-number-template.mpd"), base);

  test("enumerates video representations best-first", () => {
    expect(parsed.variants).toHaveLength(4);
    expect(parsed.variants.map((variant) => variant.id)).toEqual([
      "dash-video-avc1-4",
      "dash-video-avc1-3",
      "dash-video-avc1-2",
      "dash-video-avc1-1",
    ]);
    expect(parsed.variants[0]?.height).toBe(1080);
    expect(parsed.variants.at(-1)?.height).toBe(360);
  });

  test("a segment-templated representation is addressed by the MPD, not a file URL", () => {
    // With $Number$ there is no single URL for the rendition; ffmpeg expands the
    // manifest itself, so handing it the MPD is the correct instruction.
    expect(parsed.variants.every((variant) => variant.url === base)).toBe(true);
    expect(parsed.variants.every((variant) => variant.audioUrl === undefined)).toBe(true);
  });

  test("pairs the split audio adaptation set into every variant", () => {
    const best = parsed.variants[0];
    expect(best?.hasAudio).toBe(true);
    expect(best?.audioCodec).toBe("mp4a.40.2");
    // 4 200 000 video + 128 000 audio
    expect(best?.bitrateBps).toBe(4_328_000);
  });

  test("reads mediaPresentationDuration and estimates size from bitrate", () => {
    expect(parsed.durationSec).toBeCloseTo(634.6, 3);
    expect(parsed.isLive).toBe(false);
    const best = parsed.variants[0];
    expect(best?.filesizeIsEstimate).toBe(true);
    expect(best?.filesizeBytes).toBe(Math.round((4_328_000 * 634.6) / 8));
    expect(best?.label).toBe("1080p · H.264 + AAC · ~327 MB");
  });

  test("an unencrypted MPD is not DRM", () => {
    expect(parsed.drm).toEqual({ protected: false, systems: [] });
  });
});

describe("$Time$ SegmentTimeline manifest", () => {
  const base = "https://vod.example.net/a/b/stream.mpd";
  const parsed = parseDash(fixture("dash-time-template.mpd"), base);

  test("handles rational frame rates and both video renditions", () => {
    expect(parsed.variants).toHaveLength(2);
    expect(parsed.variants[0]?.height).toBe(720);
    expect(parsed.variants[0]?.fps).toBeCloseTo(29.97, 2);
    expect(parsed.variants[0]?.container).toBe("mp4");
    expect(parsed.durationSec).toBeCloseTo(60.08, 3);
  });

  test("resolves a subtitle BaseURL against the manifest URL", () => {
    expect(parsed.subtitles).toHaveLength(1);
    expect(parsed.subtitles[0]).toMatchObject({
      url: "https://vod.example.net/a/b/subtitles/en.vtt",
      language: "en",
      format: "vtt",
      autoGenerated: false,
    });
  });
});

describe("on-demand manifest with per-representation BaseURLs", () => {
  const parsed = parseDash(
    fixture("dash-ondemand-baseurl.mpd"),
    "https://origin.example.org/sintel.mpd",
  );

  test("an MPD-level absolute BaseURL wins over the manifest location", () => {
    expect(parsed.variants[0]?.url).toBe(
      "https://media.example.org/assets/sintel/sintel_1280x544_1250k.mp4",
    );
  });

  test("separately addressable audio becomes audioUrl for muxing", () => {
    const best = parsed.variants[0];
    expect(best?.audioUrl).toBe("https://media.example.org/assets/sintel/sintel_audio_128k.m4a");
    expect(best?.hasAudio).toBe(true);
    expect(best?.audioCodec).toBe("mp4a.40.2");
  });

  test("classifies a TTML subtitle representation", () => {
    expect(parsed.subtitles[0]).toMatchObject({
      url: "https://media.example.org/assets/sintel/sintel_de.ttml",
      language: "de",
      format: "ttml",
    });
  });
});

describe("DRM detection", () => {
  test("Widevine ContentProtection stops the pipeline and names the system", () => {
    const parsed = parseDash(fixture("dash-widevine.mpd"), "https://drm.example.net/wv/m.mpd");
    expect(parsed.drm.protected).toBe(true);
    expect(parsed.drm.systems).toContain("widevine");
    expect(parsed.drm.evidence).toContain("edef8ba9-79d6-4ace-a3c8-27dcd51d21ed");
  });

  test("PlayReady ContentProtection is named too", () => {
    const parsed = parseDash(fixture("dash-playready.mpd"), "https://drm.example.net/pr/m.mpd");
    expect(parsed.drm.protected).toBe(true);
    expect(parsed.drm.systems).toContain("playready");
    expect(parsed.drm.evidence).toContain("9a04f079-9840-4286-ab92-e65be0885f95");
  });

  // The counterpart to the HLS ClearKey tests: same key system, opposite
  // verdict, because DASH offers no fetchable-key form. The key lives behind
  // the Laurl licence endpoint, and acquiring it is a licence exchange.
  test("ClearKey is a hard stop in DASH, and says why", () => {
    const parsed = parseDash(fixture("dash-clearkey.mpd"), "https://drm.example.net/ck/m.mpd");
    expect(parsed.drm.protected).toBe(true);
    expect(parsed.drm.systems).toContain("clearkey");
    expect(parsed.drm.evidence).toContain("licence exchange required");
    expect(parsed.drm.evidence).toContain("licence URL in manifest");
  });

  test("bare Common Encryption is protected even though it names no key system", () => {
    const parsed = parseDash(
      `<?xml version="1.0"?><MPD type="static" mediaPresentationDuration="PT1M">
         <Period><AdaptationSet mimeType="video/mp4">
           <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"/>
           <SegmentTemplate media="$Number$.m4s"/>
           <Representation id="v" bandwidth="1000" codecs="avc1.4d401e" width="640" height="360"/>
         </AdaptationSet></Period></MPD>`,
      "https://x.example/m.mpd",
    );
    expect(parsed.drm.protected).toBe(true);
    expect(parsed.drm.systems).toEqual(["unknown"]);
  });
});

describe("live manifest", () => {
  const parsed = parseDash(
    fixture("dash-live-dynamic.mpd"),
    "https://live.example.com/channel-3/manifest.mpd",
  );

  test('type="dynamic" is live and carries no duration', () => {
    expect(parsed.isLive).toBe(true);
    expect(parsed.durationSec).toBeUndefined();
    expect(parsed.variants[0]?.filesizeBytes).toBeUndefined();
    expect(parsed.variants[0]?.label).toBe("720p50 · H.264 + AAC");
  });
});

describe("malformed input", () => {
  test("a body that is not an MPD falls through with NO_MEDIA_FOUND", () => {
    try {
      parseDash("<!doctype html><html><body>nope</body></html>", "https://x.example/m.mpd");
      expect.unreachable("parseDash should have thrown");
    } catch (error) {
      expect(error).toBeInstanceOf(AppError);
      expect((error as AppError).code).toBe("NO_MEDIA_FOUND");
    }
  });
});
