import { readFileSync } from "node:fs";
import { AppError } from "@downloader/contract";
import { describe, expect, test } from "vitest";
import { parseAttributeList, parseHls } from "../src/manifest/hls.ts";

function fixture(name: string): string {
  return readFileSync(new URL(`./fixtures/manifests/${name}`, import.meta.url), "utf8");
}

const MASTER_BASE = "https://cdn.example.com/hls/2026/master.m3u8";

describe("attribute lists", () => {
  test("keeps commas that live inside a quoted value", () => {
    const attrs = parseAttributeList(
      'BANDWIDTH=1352000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720,AUDIO="aac-128k"',
    );
    expect(attrs.get("CODECS")).toBe("avc1.4d401f,mp4a.40.2");
    expect(attrs.get("RESOLUTION")).toBe("1280x720");
    expect(attrs.get("AUDIO")).toBe("aac-128k");
  });
});

describe("multi-bitrate master playlist", () => {
  const parsed = parseHls(fixture("hls-master-multibitrate.m3u8"), MASTER_BASE);

  test("enumerates every EXT-X-STREAM-INF and skips I-frame trick-play streams", () => {
    expect(parsed.variants).toHaveLength(5);
    expect(parsed.variants.every((variant) => variant.protocol === "hls")).toBe(true);
    expect(parsed.variants.some((variant) => variant.url.includes("iframe"))).toBe(false);
  });

  test("orders variants best-first and resolves relative URIs", () => {
    const [best, second] = parsed.variants;
    expect(best?.height).toBe(1080);
    expect(best?.bitrateBps).toBe(7_676_642);
    expect(best?.url).toBe("https://cdn.example.com/hls/2026/v9/prog_index.m3u8");
    expect(second?.bitrateBps).toBe(5_993_827);
    expect(parsed.variants.at(-1)?.height).toBe(270);
  });

  test("reads resolution, frame rate and codecs into a human label", () => {
    const best = parsed.variants[0];
    expect(best?.fps).toBe(60);
    expect(best?.videoCodec).toBe("avc1.64002a");
    expect(best?.audioCodec).toBe("mp4a.40.2");
    expect(best?.hasVideo).toBe(true);
    expect(best?.hasAudio).toBe(true);
    expect(best?.label).toBe("1080p60 · H.264 + AAC");
  });

  test("a master playlist is not DRM and not live", () => {
    expect(parsed.drm).toEqual({ protected: false, systems: [] });
    expect(parsed.isLive).toBe(false);
  });
});

describe("master playlist with split audio and subtitles", () => {
  const parsed = parseHls(fixture("hls-master-split-audio.m3u8"), MASTER_BASE);

  test("points each variant at the default rendition of its audio group", () => {
    const aac = parsed.variants.find((variant) => variant.bitrateBps === 3_900_000);
    expect(aac?.audioUrl).toBe("https://cdn.example.com/hls/2026/audio/en/128k/playlist.m3u8");
    expect(aac?.language).toBe("en");

    const dolby = parsed.variants.find((variant) => variant.audioCodec === "ec-3");
    expect(dolby?.audioUrl).toBe("https://cdn.example.com/hls/2026/audio/en/384k/playlist.m3u8");
    expect(dolby?.label).toContain("E-AC-3");
  });

  test("a video-only CODECS list still has audio when an audio group is attached", () => {
    const videoOnly = parsed.variants.find((variant) => variant.height === 360);
    expect(videoOnly?.videoCodec).toBe("avc1.4d401e");
    expect(videoOnly?.audioCodec).toBeUndefined();
    expect(videoOnly?.hasAudio).toBe(true);
    expect(videoOnly?.audioUrl).toBe(
      "https://cdn.example.com/hls/2026/audio/en/128k/playlist.m3u8",
    );
  });

  test("collects subtitle renditions and ignores in-band closed captions", () => {
    expect(parsed.subtitles).toHaveLength(2);
    expect(parsed.subtitles.map((track) => track.language)).toEqual(["en", "fr"]);
    expect(parsed.subtitles[0]).toMatchObject({
      url: "https://cdn.example.com/hls/2026/subtitles/en/playlist.m3u8",
      format: "vtt",
      autoGenerated: false,
    });
  });
});

describe("AES-128 media playlist", () => {
  const base = "https://cdn.example.com/courses/lesson-42/index.m3u8";
  const parsed = parseHls(fixture("hls-media-aes128.m3u8"), base);

  test("an in-manifest key URI is transport encryption, NOT DRM", () => {
    expect(parsed.drm.protected).toBe(false);
    expect(parsed.drm.systems).toEqual([]);
    expect(parsed.drm.evidence).toMatch(/not DRM/i);
  });

  test("sums EXTINF into a duration and reports VOD", () => {
    expect(parsed.isLive).toBe(false);
    expect(parsed.durationSec).toBeCloseTo(56.557, 3);
  });

  test("yields one variant addressed by the playlist itself", () => {
    expect(parsed.variants).toHaveLength(1);
    expect(parsed.variants[0]).toMatchObject({
      id: "hls-media",
      url: base,
      protocol: "hls",
      container: "mpegts",
      hasVideo: true,
      hasAudio: true,
    });
  });
});

describe("live media playlist", () => {
  const parsed = parseHls(
    fixture("hls-media-live.m3u8"),
    "https://live.example.com/channel/master_1080p.m3u8",
  );

  test("a missing EXT-X-ENDLIST means live, and live means no known duration", () => {
    expect(parsed.isLive).toBe(true);
    expect(parsed.durationSec).toBeUndefined();
    expect(parsed.variants[0]?.durationSec).toBeUndefined();
    expect(parsed.variants[0]?.label).toBe("Live HLS stream");
  });
});

describe("DRM detection", () => {
  test("FairPlay: SAMPLE-AES with an skd:// key URI stops the pipeline", () => {
    const parsed = parseHls(fixture("hls-master-fairplay.m3u8"), MASTER_BASE);
    expect(parsed.drm.protected).toBe(true);
    expect(parsed.drm.systems).toEqual(["fairplay"]);
    expect(parsed.drm.evidence).toContain("skd://");
  });

  test("Widevine and PlayReady KEYFORMATs are both named", () => {
    const parsed = parseHls(fixture("hls-media-widevine.m3u8"), MASTER_BASE);
    expect(parsed.drm.protected).toBe(true);
    expect(parsed.drm.systems).toContain("widevine");
    expect(parsed.drm.systems).toContain("playready");
    expect(parsed.drm.evidence).toContain("edef8ba9-79d6-4ace-a3c8-27dcd51d21ed");
  });

  test("an unrecognised non-identity KEYFORMAT is still treated as a key system", () => {
    const parsed = parseHls(
      [
        "#EXTM3U",
        "#EXT-X-TARGETDURATION:4",
        '#EXT-X-KEY:METHOD=SAMPLE-AES,KEYFORMAT="com.example.newdrm",URI="https://k/1"',
        "#EXTINF:4.0,",
        "a.ts",
        "#EXT-X-ENDLIST",
      ].join("\n"),
      MASTER_BASE,
    );
    expect(parsed.drm.protected).toBe(true);
    expect(parsed.drm.systems).toEqual(["unknown"]);
  });

  // The ClearKey boundary. It abuts the DRM hard stop, so both sides are
  // pinned: what makes a case downloadable is that the key is one plain GET
  // away, never the name of the key system.
  test("ClearKey with a fetchable key URI is transport encryption, not DRM", () => {
    const parsed = parseHls(
      fixture("hls-media-clearkey-fetchable.m3u8"),
      "https://cdn.example.com/courses/lesson-42/index.m3u8",
    );
    expect(parsed.drm.protected).toBe(false);
    // Recorded even though it is permitted, so a caller can still see ClearKey
    // was in play rather than having to infer it from silence.
    expect(parsed.drm.systems).toEqual(["clearkey"]);
    expect(parsed.drm.evidence).toContain("fetchable URI");
  });

  test("a relative ClearKey key URI is fetchable too — it resolves against the playlist", () => {
    const parsed = parseHls(
      [
        "#EXTM3U",
        "#EXT-X-TARGETDURATION:4",
        '#EXT-X-KEY:METHOD=AES-128,KEYFORMAT="org.w3.clearkey",URI="keys/ck.bin"',
        "#EXTINF:4.0,",
        "a.ts",
        "#EXT-X-ENDLIST",
      ].join("\n"),
      MASTER_BASE,
    );
    expect(parsed.drm.protected).toBe(false);
  });

  test("ClearKey needing a licence exchange remains a hard stop", () => {
    const parsed = parseHls(
      fixture("hls-media-clearkey-licence.m3u8"),
      "https://cdn.example.com/courses/lesson-42/index.m3u8",
    );
    expect(parsed.drm.protected).toBe(true);
    expect(parsed.drm.systems).toEqual(["clearkey"]);
    expect(parsed.drm.evidence).toContain("licence exchange");
  });

  test("one protected key poisons a playlist that also has a fetchable one", () => {
    const parsed = parseHls(
      [
        "#EXTM3U",
        "#EXT-X-TARGETDURATION:4",
        '#EXT-X-KEY:METHOD=AES-128,KEYFORMAT="org.w3.clearkey",URI="https://k/ck"',
        "#EXTINF:4.0,",
        "a.ts",
        '#EXT-X-KEY:METHOD=SAMPLE-AES,KEYFORMAT="com.widevine.alpha",URI="https://k/wv"',
        "#EXTINF:4.0,",
        "b.ts",
        "#EXT-X-ENDLIST",
      ].join("\n"),
      MASTER_BASE,
    );
    // Half a file presented as a whole one is worse than an honest refusal.
    expect(parsed.drm.protected).toBe(true);
    expect(parsed.drm.systems).toEqual(["widevine"]);
  });

  test("METHOD=NONE is not encryption at all", () => {
    const parsed = parseHls(
      ["#EXTM3U", "#EXT-X-KEY:METHOD=NONE", "#EXTINF:4.0,", "a.ts", "#EXT-X-ENDLIST"].join("\n"),
      MASTER_BASE,
    );
    expect(parsed.drm).toEqual({ protected: false, systems: [] });
  });
});

describe("malformed input", () => {
  test("a body that is not a playlist falls through with NO_MEDIA_FOUND", () => {
    try {
      parseHls("<!doctype html><html><body>404</body></html>", MASTER_BASE);
      expect.unreachable("parseHls should have thrown");
    } catch (error) {
      expect(error).toBeInstanceOf(AppError);
      expect((error as AppError).code).toBe("NO_MEDIA_FOUND");
    }
  });

  test("an empty playlist yields no variants rather than throwing", () => {
    const parsed = parseHls("#EXTM3U\n#EXT-X-VERSION:3\n", MASTER_BASE);
    expect(parsed.variants).toEqual([]);
    expect(parsed.isLive).toBe(false);
  });
});
