import { readFileSync } from "node:fs";
import { AppError } from "@downloader/contract";
import { describe, expect, test } from "vitest";
import { parseAttributeList, parseHls } from "../src/manifest/hls.ts";

function fixture(name: string): string {
  return readFileSync(new URL(`./fixtures/manifests/${name}`, import.meta.url), "utf8");
}

const MASTER_BASE = "https://cdn.example.com/hls/2026/master.m3u8";

/** Every address the parser says will serve one rendition, primary first (dl-45). */
function addresses(variant: {
  url: string;
  alternateUrls?: readonly string[] | undefined;
}): string[] {
  return [variant.url, ...(variant.alternateUrls ?? [])];
}

describe("attribute lists", () => {
  test("keeps commas that live inside a quoted value", () => {
    const attrs = parseAttributeList(
      'BANDWIDTH=1352000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720,AUDIO="aac-128k"',
    );
    expect(attrs.get("CODECS")).toBe("avc1.4d401f,mp4a.40.2");
    expect(attrs.get("RESOLUTION")).toBe("1280x720");
    expect(attrs.get("AUDIO")).toBe("aac-128k");
  });
});

describe("multi-bitrate master playlist", () => {
  const parsed = parseHls(fixture("hls-master-multibitrate.m3u8"), MASTER_BASE);

  test("enumerates every EXT-X-STREAM-INF and skips I-frame trick-play streams", () => {
    expect(parsed.variants).toHaveLength(5);
    expect(parsed.variants.every((variant) => variant.protocol === "hls")).toBe(true);
    expect(parsed.variants.some((variant) => variant.url.includes("iframe"))).toBe(false);
  });

  test("orders variants best-first and resolves relative URIs", () => {
    const [best, second] = parsed.variants;
    expect(best?.height).toBe(1080);
    expect(best?.bitrateBps).toBe(7_676_642);
    expect(best?.url).toBe("https://cdn.example.com/hls/2026/v9/prog_index.m3u8");
    expect(second?.bitrateBps).toBe(5_993_827);
    expect(parsed.variants.at(-1)?.height).toBe(270);
  });

  test("reads resolution, frame rate and codecs into a human label", () => {
    const best = parsed.variants[0];
    expect(best?.fps).toBe(60);
    expect(best?.videoCodec).toBe("avc1.64002a");
    expect(best?.audioCodec).toBe("mp4a.40.2");
    expect(best?.hasVideo).toBe(true);
    expect(best?.hasAudio).toBe(true);
    expect(best?.label).toBe("1080p60 · H.264 + AAC");
  });

  test("a master playlist is not DRM and not live", () => {
    expect(parsed.drm).toEqual({ protected: false, systems: [] });
    expect(parsed.isLive).toBe(false);
  });
});

describe("master playlist with split audio and subtitles", () => {
  const parsed = parseHls(fixture("hls-master-split-audio.m3u8"), MASTER_BASE);

  test("points each variant at the default rendition of its audio group", () => {
    const aac = parsed.variants.find((variant) => variant.bitrateBps === 3_900_000);
    expect(aac?.audioUrl).toBe("https://cdn.example.com/hls/2026/audio/en/128k/playlist.m3u8");
    expect(aac?.language).toBe("en");

    const dolby = parsed.variants.find((variant) => variant.audioCodec === "ec-3");
    expect(dolby?.audioUrl).toBe("https://cdn.example.com/hls/2026/audio/en/384k/playlist.m3u8");
    expect(dolby?.label).toContain("E-AC-3");
  });

  test("a video-only CODECS list still has audio when an audio group is attached", () => {
    const videoOnly = parsed.variants.find((variant) => variant.height === 360);
    expect(videoOnly?.videoCodec).toBe("avc1.4d401e");
    expect(videoOnly?.audioCodec).toBeUndefined();
    expect(videoOnly?.hasAudio).toBe(true);
    expect(videoOnly?.audioUrl).toBe(
      "https://cdn.example.com/hls/2026/audio/en/128k/playlist.m3u8",
    );
  });

  test("collects subtitle renditions and ignores in-band closed captions", () => {
    expect(parsed.subtitles).toHaveLength(2);
    expect(parsed.subtitles.map((track) => track.language)).toEqual(["en", "fr"]);
    expect(parsed.subtitles[0]).toMatchObject({
      url: "https://cdn.example.com/hls/2026/subtitles/en/playlist.m3u8",
      format: "vtt",
      autoGenerated: false,
    });
  });
});

describe("AES-128 media playlist", () => {
  const base = "https://cdn.example.com/courses/lesson-42/index.m3u8";
  const parsed = parseHls(fixture("hls-media-aes128.m3u8"), base);

  test("an in-manifest key URI is transport encryption, NOT DRM", () => {
    expect(parsed.drm.protected).toBe(false);
    expect(parsed.drm.systems).toEqual([]);
    expect(parsed.drm.evidence).toMatch(/not DRM/i);
  });

  test("sums EXTINF into a duration and reports VOD", () => {
    expect(parsed.isLive).toBe(false);
    expect(parsed.durationSec).toBeCloseTo(56.557, 3);
  });

  test("yields one variant addressed by the playlist itself", () => {
    expect(parsed.variants).toHaveLength(1);
    expect(parsed.variants[0]).toMatchObject({
      id: "hls-media",
      url: base,
      protocol: "hls",
      container: "mpegts",
      hasVideo: true,
      hasAudio: true,
    });
  });
});

describe("live media playlist", () => {
  const parsed = parseHls(
    fixture("hls-media-live.m3u8"),
    "https://live.example.com/channel/master_1080p.m3u8",
  );

  test("a missing EXT-X-ENDLIST means live, and live means no known duration", () => {
    expect(parsed.isLive).toBe(true);
    expect(parsed.durationSec).toBeUndefined();
    expect(parsed.variants[0]?.durationSec).toBeUndefined();
    expect(parsed.variants[0]?.label).toBe("Live HLS stream");
  });
});

describe("DRM detection", () => {
  test("FairPlay: SAMPLE-AES with an skd:// key URI stops the pipeline", () => {
    const parsed = parseHls(fixture("hls-master-fairplay.m3u8"), MASTER_BASE);
    expect(parsed.drm.protected).toBe(true);
    expect(parsed.drm.systems).toEqual(["fairplay"]);
    expect(parsed.drm.evidence).toContain("skd://");
  });

  test("Widevine and PlayReady KEYFORMATs are both named", () => {
    const parsed = parseHls(fixture("hls-media-widevine.m3u8"), MASTER_BASE);
    expect(parsed.drm.protected).toBe(true);
    expect(parsed.drm.systems).toContain("widevine");
    expect(parsed.drm.systems).toContain("playready");
    expect(parsed.drm.evidence).toContain("edef8ba9-79d6-4ace-a3c8-27dcd51d21ed");
  });

  test("an unrecognised non-identity KEYFORMAT is still treated as a key system", () => {
    const parsed = parseHls(
      [
        "#EXTM3U",
        "#EXT-X-TARGETDURATION:4",
        '#EXT-X-KEY:METHOD=SAMPLE-AES,KEYFORMAT="com.example.newdrm",URI="https://k/1"',
        "#EXTINF:4.0,",
        "a.ts",
        "#EXT-X-ENDLIST",
      ].join("\n"),
      MASTER_BASE,
    );
    expect(parsed.drm.protected).toBe(true);
    expect(parsed.drm.systems).toEqual(["unknown"]);
  });

  // The ClearKey boundary. It abuts the DRM hard stop, so both sides are
  // pinned: what makes a case downloadable is that the key is one plain GET
  // away, never the name of the key system.
  test("ClearKey with a fetchable key URI is transport encryption, not DRM", () => {
    const parsed = parseHls(
      fixture("hls-media-clearkey-fetchable.m3u8"),
      "https://cdn.example.com/courses/lesson-42/index.m3u8",
    );
    expect(parsed.drm.protected).toBe(false);
    // Recorded even though it is permitted, so a caller can still see ClearKey
    // was in play rather than having to infer it from silence.
    expect(parsed.drm.systems).toEqual(["clearkey"]);
    expect(parsed.drm.evidence).toContain("fetchable URI");
  });

  test("a relative ClearKey key URI is fetchable too — it resolves against the playlist", () => {
    const parsed = parseHls(
      [
        "#EXTM3U",
        "#EXT-X-TARGETDURATION:4",
        '#EXT-X-KEY:METHOD=AES-128,KEYFORMAT="org.w3.clearkey",URI="keys/ck.bin"',
        "#EXTINF:4.0,",
        "a.ts",
        "#EXT-X-ENDLIST",
      ].join("\n"),
      MASTER_BASE,
    );
    expect(parsed.drm.protected).toBe(false);
  });

  test("ClearKey needing a licence exchange remains a hard stop", () => {
    const parsed = parseHls(
      fixture("hls-media-clearkey-licence.m3u8"),
      "https://cdn.example.com/courses/lesson-42/index.m3u8",
    );
    expect(parsed.drm.protected).toBe(true);
    expect(parsed.drm.systems).toEqual(["clearkey"]);
    expect(parsed.drm.evidence).toContain("licence exchange");
  });

  test("one protected key poisons a playlist that also has a fetchable one", () => {
    const parsed = parseHls(
      [
        "#EXTM3U",
        "#EXT-X-TARGETDURATION:4",
        '#EXT-X-KEY:METHOD=AES-128,KEYFORMAT="org.w3.clearkey",URI="https://k/ck"',
        "#EXTINF:4.0,",
        "a.ts",
        '#EXT-X-KEY:METHOD=SAMPLE-AES,KEYFORMAT="com.widevine.alpha",URI="https://k/wv"',
        "#EXTINF:4.0,",
        "b.ts",
        "#EXT-X-ENDLIST",
      ].join("\n"),
      MASTER_BASE,
    );
    // Half a file presented as a whole one is worse than an honest refusal.
    expect(parsed.drm.protected).toBe(true);
    expect(parsed.drm.systems).toEqual(["widevine"]);
  });

  test("METHOD=NONE is not encryption at all", () => {
    const parsed = parseHls(
      ["#EXTM3U", "#EXT-X-KEY:METHOD=NONE", "#EXTINF:4.0,", "a.ts", "#EXT-X-ENDLIST"].join("\n"),
      MASTER_BASE,
    );
    expect(parsed.drm).toEqual({ protected: false, systems: [] });
  });
});

describe("malformed input", () => {
  test("a body that is not a playlist falls through with NO_MEDIA_FOUND", () => {
    try {
      parseHls("<!doctype html><html><body>404</body></html>", MASTER_BASE);
      expect.unreachable("parseHls should have thrown");
    } catch (error) {
      expect(error).toBeInstanceOf(AppError);
      expect((error as AppError).code).toBe("NO_MEDIA_FOUND");
    }
  });

  test("an empty playlist yields no variants rather than throwing", () => {
    const parsed = parseHls("#EXTM3U\n#EXT-X-VERSION:3\n", MASTER_BASE);
    expect(parsed.variants).toEqual([]);
    expect(parsed.isLive).toBe(false);
  });
});

/**
 * The shapes dl-40 is about, and the claim each fixture makes.
 *
 * All three were emitted by ffmpeg rather than typed here, and the header
 * comment in each `.m3u8` carries the command that produced it. That is the
 * difference between a fixture and an assumption: a hand-written playlist
 * holding copies of one invented line would pass against an implementation that
 * collapsed any two rows at all, and would prove nothing about a real ladder.
 *
 * The mirror fixture is the reported one, established by a live probe rather
 * than inferred — but with the mirror count varied per rung, because the
 * reported manifest had exactly two everywhere and a fixture that copied that
 * would let an implementation hardcode two.
 *
 * dl-45 moved where the mirror fixture's claim lands without touching the
 * fixture itself: the `.m3u8` is byte-identical, and what changed is that the
 * grouping now happens in this parser rather than in the picker. The other two
 * fixtures are the guard on that — they must survive it untouched, because a
 * grouping key that lost a field would merge a real choice into a failover path.
 */
describe("renditions that differ only in what the picker cannot show (dl-40, dl-45)", () => {
  const redundant = parseHls(
    fixture("hls-master-redundant-mirrors.m3u8"),
    "https://vod-a.cdn.example/hls/reported/master.m3u8",
  );

  test("a mirrored master yields one variant per rung, carrying the other hosts (dl-45)", () => {
    // This is the claim dl-45 inverted. Until it, the parser emitted one variant
    // per *declaration* and the ten of them reached the picker, which collapsed
    // them back to five and threw the alternates away. Now the grouping happens
    // here, where the mirrors are known to be mirrors, and nothing is discarded.
    expect(redundant.variants).toHaveLength(5);
    expect(redundant.variants.map((variant) => variant.height)).toEqual([720, 480, 360, 240, 144]);

    // The declared counts are unchanged — 3, 2, 2, 1, 2 — they are just counted
    // per rendition now instead of per row. A rung with one mirror and a rung
    // with three both have to work.
    const perRung = redundant.variants.map((variant) => addresses(variant).length);
    expect(perRung).toEqual([3, 2, 2, 1, 2]);

    // All ten addresses the manifest declared are still here, and still distinct:
    // grouping moved them, it did not drop them.
    const all = redundant.variants.flatMap(addresses);
    expect(all).toHaveLength(10);
    expect(new Set(all).size).toBe(10);

    // The primary is the first the manifest declared for that rung.
    expect(redundant.variants.map((variant) => new URL(variant.url).host)).toEqual(
      Array.from({ length: 5 }, () => "vod-a.cdn.example"),
    );
  });

  test("one rung at two hosts is one variant carrying the second host as an alternate", () => {
    // The Done-when line, on the smallest rung that has a mirror at all: 480p is
    // declared twice, and what comes out is *one* variant, not two.
    const rung = redundant.variants.filter((variant) => variant.height === 480);
    expect(rung).toHaveLength(1);
    expect(rung[0]?.url).toBe("https://vod-a.cdn.example/1/index.m3u8");
    expect(rung[0]?.alternateUrls).toEqual(["https://vod-b.cdn.example/1/index.m3u8"]);
  });

  test("a rung with no mirror carries no alternates at all, rather than an empty list", () => {
    // `[]` and absent are different claims on the wire, and the picker renders
    // the count off this: an empty array would still say "1", but it would also
    // put a field on every unmirrored variant in every probe.
    const lonely = redundant.variants.filter((variant) => variant.height === 240);
    expect(lonely).toHaveLength(1);
    expect(lonely[0] === undefined ? true : "alternateUrls" in lonely[0]).toBe(false);
  });

  test("inside one rung the host is the only thing that differs at all", () => {
    const rung = redundant.variants.find((variant) => variant.height === 720);
    expect(rung).toBeDefined();

    // The URLs agree on everything except the host — which is what the live
    // probe of the reported video found, and is why the rows were identical.
    const urls = addresses(rung ?? { url: "" }).map((url) => new URL(url));
    expect(urls).toHaveLength(3);
    expect(new Set(urls.map((url) => url.host)).size).toBe(3);
    expect(new Set(urls.map((url) => `${url.protocol}${url.pathname}${url.search}`)).size).toBe(1);

    // That they agree on every *attribute* is now asserted by the grouping
    // itself — `renditionKey` compares whole variants minus `id`, `url` and
    // `alternateUrls`, so a rung whose entries disagreed anywhere would have
    // come out as more than one variant and the length above would have caught
    // it. The two fixtures below are the other direction of that same guard.

    // Nothing in that rung carries a language — the reported manifest declared
    // no EXT-X-MEDIA at all, which is what makes it the *other* branch of dl-40
    // from the fixture below.
    expect(rung?.language).toBeUndefined();
  });

  test("two profiles of one rung differ in the codec string and nowhere else", () => {
    const parsed = parseHls(fixture("hls-master-two-profiles.m3u8"), MASTER_BASE);
    const rung = parsed.variants.filter((variant) => variant.height === 720);
    expect(rung).toHaveLength(2);
    // High and Baseline. `shortCodec` renders both as "H.264", which is what
    // makes this the shape a rendered-columns-only collapse would destroy.
    expect(rung.map((variant) => variant.videoCodec)).toEqual(["avc1.64001f", "avc1.42c01f"]);
    expect(new Set(rung.map((variant) => variant.bitrateBps)).size).toBe(1);
    expect(rung.every((variant) => variant.language === undefined)).toBe(true);
    // And dl-45 did not swallow them: two profiles are two renditions, so the
    // mirror grouping must leave both alone. This is the failure mode of a key
    // that dropped a field — silently merging a real choice into an alternate.
    expect(rung.every((variant) => variant.alternateUrls === undefined)).toBe(true);
  });

  test("a per-language ladder repeats the same rungs but disagrees on language", () => {
    const parsed = parseHls(fixture("hls-master-per-language-ladder.m3u8"), MASTER_BASE);
    expect(parsed.variants).toHaveLength(4);

    const rung = parsed.variants.filter((variant) => variant.height === 720);
    expect(rung).toHaveLength(2);
    expect(rung.map((variant) => variant.language)).toEqual(["eng", "fra"]);
    expect(new Set(rung.map((variant) => variant.bitrateBps)).size).toBe(1);
    expect(new Set(rung.map((variant) => variant.videoCodec)).size).toBe(1);
    // Same guard as above, on the field the two rungs actually differ in: two
    // languages are two renditions and neither is the other's failover path.
    expect(rung.every((variant) => variant.alternateUrls === undefined)).toBe(true);
  });
});

/**
 * The `.variants.json` beside each manifest is the web picker's fixture: that
 * suite cannot run this parser — importing `@downloader/resolvers` from a jsdom
 * test would drag playwright in — so it reads what the parser produced rather
 * than hand-building variants that would drift from it.
 *
 * This test is what stops the drift. Regenerate a file from the parser when it
 * fails; never edit the JSON to match a new expectation, which would quietly
 * re-point the web suite at something no manifest yields.
 */
describe("derived variant fixtures (dl-40)", () => {
  const derived = [
    "hls-master-redundant-mirrors",
    "hls-master-per-language-ladder",
    "hls-master-two-profiles",
    "hls-master-multibitrate",
  ];

  for (const name of derived) {
    test(`${name}.variants.json is what parseHls returns today`, () => {
      const record = JSON.parse(fixture(`${name}.variants.json`)) as {
        producer: string;
        source: string;
        baseUrl: string;
        variants: unknown;
      };
      // The source and the base URL come out of the file itself, so the guard
      // can never be checking a different playlist than the one it names.
      expect(record.producer).toBe("parseHls");
      expect(record.source).toBe(`${name}.m3u8`);
      expect(parseHls(fixture(record.source), record.baseUrl).variants).toEqual(record.variants);
    });
  }
});
