/**
 * dl-45 end to end: the second server a player would have tried.
 *
 * A real HLS stream generated by the bundled ffmpeg, served from a local origin,
 * with the *primary* address pointed somewhere that fails. Nothing here mocks a
 * retry counter or stubs the downloader — the failure is a real one from a real
 * socket, and the success is a real MP4 on disk that ffmpeg can decode.
 *
 * The two cases pull in opposite directions and that is the whole test:
 *
 *  - **the host will not answer** → the engine must reach the mirror;
 *  - **the URL is expired (403)** → the engine must *not*, because the alternate
 *    is expired too and burning it would displace the orchestrator's re-probe.
 *
 * The second is asserted from the mirror's own request log rather than from the
 * error code: "it failed with the same code" would also be true of an engine
 * that tried the mirror, got the same 403, and gave up. Zero requests is the
 * only thing that says it never tried.
 */

import { spawn } from "node:child_process";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterAll, beforeAll, expect, test } from "vitest";
import type { MediaVariant, RequestContext } from "@downloader/contract";
import { resolveFfmpegPath } from "../src/config.ts";
import { createEngine } from "../src/index.ts";
import type { FixtureServer } from "./helpers/http.ts";
import { startFixtureServer } from "./helpers/http.ts";

const FFMPEG = resolveFfmpegPath();
const CLIP_SECONDS = 2;

const CONTEXT: RequestContext = {
  headers: { Referer: "https://player.example/watch/45", "User-Agent": "Mozilla/5.0 (Fixture)" },
};

const CONTENT_TYPES: Record<string, string> = {
  ".m3u8": "application/vnd.apple.mpegurl",
  ".ts": "video/mp2t",
};

let fixtureDir: string;
let storageDir: string;
/** Serves the stream. In every test here this is the *mirror*, never the primary. */
let mirror: FixtureServer;
/** Answers 403 to everything, standing in for a signed URL that has expired. */
let expired: FixtureServer;
/** An address nothing is listening on: a port we bound and then released. */
let deadOrigin: string;

function runFfmpeg(args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(FFMPEG, args, {
      shell: false,
      windowsHide: true,
      stdio: ["ignore", "ignore", "pipe"],
    });
    let stderr = "";
    child.stderr?.setEncoding("utf8");
    child.stderr?.on("data", (chunk: string) => {
      stderr += chunk;
    });
    child.once("error", reject);
    child.once("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`ffmpeg exited ${code}: ${stderr.slice(-2000)}`));
    });
  });
}

beforeAll(async () => {
  fixtureDir = await fs.mkdtemp(path.join(os.tmpdir(), "engine-mirror-fixture-"));
  storageDir = await fs.mkdtemp(path.join(os.tmpdir(), "engine-mirror-storage-"));

  await runFfmpeg([
    "-hide_banner",
    "-nostdin",
    "-loglevel",
    "error",
    "-y",
    "-f",
    "lavfi",
    "-i",
    `testsrc=size=160x120:rate=10:duration=${CLIP_SECONDS}`,
    "-f",
    "lavfi",
    "-i",
    `sine=frequency=440:sample_rate=44100:duration=${CLIP_SECONDS}`,
    "-c:v",
    "libx264",
    "-preset",
    "ultrafast",
    "-pix_fmt",
    "yuv420p",
    "-g",
    "10",
    "-c:a",
    "aac",
    "-b:a",
    "64k",
    "-f",
    "hls",
    "-hls_time",
    "1",
    "-hls_list_size",
    "0",
    "-hls_playlist_type",
    "vod",
    "-hls_segment_filename",
    path.join(fixtureDir, "seg%03d.ts"),
    path.join(fixtureDir, "index.m3u8"),
  ]);

  mirror = await startFixtureServer(async (request, response) => {
    const name = path.basename(new URL(request.url ?? "/", "http://x").pathname);
    let body: Buffer;
    try {
      body = await fs.readFile(path.join(fixtureDir, name));
    } catch {
      response.writeHead(404).end();
      return;
    }
    response.writeHead(200, {
      "content-type": CONTENT_TYPES[path.extname(name)] ?? "application/octet-stream",
      "content-length": String(body.length),
    });
    response.end(body);
  });

  expired = await startFixtureServer((_request, response) => {
    response.writeHead(403, { "content-type": "text/plain" }).end("expired");
  });

  // A refused connection, without assuming any particular port is free: bind an
  // ephemeral one, remember it, and give it back. Nothing is listening there
  // when the engine dials it, so the kernel answers with ECONNREFUSED and
  // ffmpeg writes `Connection to tcp://… failed: Connection refused`.
  const transient = await startFixtureServer((_request, response) => {
    response.end();
  });
  deadOrigin = transient.origin;
  await transient.close();
});

afterAll(async () => {
  await mirror?.close();
  await expired?.close();
  await fs.rm(fixtureDir, { recursive: true, force: true });
  await fs.rm(storageDir, { recursive: true, force: true });
});

function variant(primaryOrigin: string): MediaVariant {
  return {
    id: "v0",
    protocol: "hls",
    url: `${primaryOrigin}/index.m3u8`,
    alternateUrls: [`${mirror.origin}/index.m3u8`],
    hasVideo: true,
    hasAudio: true,
    videoCodec: "avc1.42c01e",
    audioCodec: "mp4a.40.2",
    width: 160,
    height: 120,
    durationSec: CLIP_SECONDS,
    label: "120p",
  };
}

test("a host that refuses the connection is failed over to the mirror", async () => {
  const engine = createEngine({ storageDir, maxFileSizeBytes: 64 * 1024 * 1024 });
  await engine.init();

  const before = mirror.requests.length;
  const outcome = await engine.download({
    jobId: "mirror-ok",
    variant: variant(deadOrigin),
    requestContext: CONTEXT,
    title: "failed over",
    durationSec: CLIP_SECONDS,
  });

  // A finished file, not merely a promise that resolved.
  expect(outcome.sizeBytes).toBeGreaterThan(1000);
  await runFfmpeg([
    "-hide_banner",
    "-nostdin",
    "-loglevel",
    "error",
    "-xerror",
    "-i",
    outcome.path,
    "-f",
    "null",
    "-",
  ]);

  // And it came from the second host: the playlist and its segments were all
  // fetched from the mirror, which is the only origin still listening.
  const served = mirror.requests.slice(before);
  expect(served.some((request) => request.url.endsWith("index.m3u8"))).toBe(true);
  expect(served.filter((request) => request.url.endsWith(".ts")).length).toBeGreaterThan(0);
});

test("an expired signed URL never reaches the mirror — it is expired there too", async () => {
  const engine = createEngine({ storageDir });
  await engine.init();

  const before = mirror.requests.length;
  await expect(
    engine.download({
      jobId: "mirror-expired",
      variant: variant(expired.origin),
      requestContext: CONTEXT,
      title: "expired",
      durationSec: CLIP_SECONDS,
    }),
  ).rejects.toMatchObject({ code: "DOWNLOAD_FAILED" });

  // The load-bearing assertion. `DOWNLOAD_FAILED` is in `REPROBE_WORTHY`, so
  // the orchestrator re-probes exactly as it did before dl-45 — but only
  // because the alternate was left unspent, which is what this counts.
  expect(mirror.requests.slice(before)).toHaveLength(0);
});

test("the last candidate's own failure is what reaches the caller", async () => {
  // The bound on dl-45's overridden objection, and it is a general property
  // rather than a TLS one: the loop advances on a host failure and rethrows
  // whatever the *final* attempt raised. It never substitutes the first error,
  // and it never degrades a specific code into a generic one.
  //
  // Primary is a dead port (a host failure — the loop advances); the alternate
  // 403s (not a host failure — it propagates). So the error the caller sees is
  // the *second* host's, which is the half that would be silently lost if the
  // loop remembered the first error instead. It also proves the loop stops:
  // there is no third candidate and no third request.
  const engine = createEngine({ storageDir });
  await engine.init();

  const before = { mirror: mirror.requests.length, expired: expired.requests.length };
  await expect(
    engine.download({
      jobId: "mirror-last-error",
      variant: { ...variant(deadOrigin), alternateUrls: [`${expired.origin}/index.m3u8`] },
      requestContext: CONTEXT,
      title: "both bad",
      durationSec: CLIP_SECONDS,
    }),
  ).rejects.toMatchObject({ code: "DOWNLOAD_FAILED" });

  // The alternate really was tried — otherwise this test would pass on an engine
  // that never failed over at all.
  expect(expired.requests.length).toBeGreaterThan(before.expired);
  // And the healthy mirror was never involved: it is not in this variant's list.
  expect(mirror.requests).toHaveLength(before.mirror);
});

test("with no mirror to try, a dead host fails as it always did", async () => {
  const engine = createEngine({ storageDir });
  await engine.init();

  const alone = { ...variant(deadOrigin) };
  delete alone.alternateUrls;

  await expect(
    engine.download({
      jobId: "mirror-none",
      variant: alone,
      requestContext: CONTEXT,
      title: "no mirror",
      durationSec: CLIP_SECONDS,
    }),
  ).rejects.toMatchObject({ code: "DOWNLOAD_FAILED" });
});
